### ISSUE TITLE
what's up with all the scroll bars?

### ISSUE THREAD

**Issue by johnny-smitherson** [hyperdiv/hyperdiv#11] opened 2024-02-22 12:33 UTC
<img width="936" alt="scrollbars" src="https://github.com/hyperdiv/hyperdiv/assets/127537716/2adf06a0-67ba-4ef5-8388-022c8f363110">

the ones at the bottom also show up in the `template.add_sidebar_menu` example

**Comment by mariusnita** [comment] 2024-02-22 19:12
Hi, thanks! Having a hard time repro-ing on macOS Firefox/Chome/Safari. Do you see these in every code box, or just on this page? What browser/os?

**Comment by sphars** [comment] 2024-02-27 05:31
I noticed this too. I see unnecessary horizontal scrollbars on nearly all `box` components. I can reproduce this by resizing the browser size, see video: 
[video.webm](https://github.com/hyperdiv/hyperdiv/assets/18315081/a133c09f-181b-4f83-9a5f-630d3465e417)

If I had to take a guess, I'm thinking it's due to the `box` components having the `overflow-x` CSS attribute set to `scroll` when setting the component to scroll horizontally. I wonder if that should be set to `auto` instead? Possibly same goes for `overscroll-y` on vertical scrolling boxes. 

This double scroll bar issue specifically occurs with code boxes because the `pre` elements have `overflow: auto` (which makes sense because it's a `pre` and should scroll if it needs too), but because they're contained in a div with the `.box` class, that adds the second scrollbar when the screen is small. But the box container doesn't need to scroll because the `pre` takes care of that.

I (briefly) looked through the code, and I think it may be just changing [this line](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/hyperdiv/component_mixins/boxy.py#L58) from `scroll` to `auto`. In my browser inspector, changing `scroll` -> `auto` removes the double scroll bar (just had to do it for every component). May need more thorough testing though, this was very quick glance 😅

**Comment by mariusnita** [comment] 2024-02-28 21:10
@sphars thanks for investigating! I changed the default to "auto", as well as a specific fix for the code boxes in the docs section. The code box container was set to `horizontal_scroll=True`, but this should really be `False` (`overflow-x: hidden`) because the inner code box is already `overflow-x: auto`.

Will be in next release.

**Comment by mariusnita** [comment] 2024-03-01 21:41
Do you guys mind testing if the extraneous scrollbars are gone in the latest release? Here's the new docs app https://docs.hyperdiv.io/

**Comment by sphars** [comment] 2024-03-02 04:19
Confirmed, I'm not seeing any unnecessary scroll bars now (tested in Firefox and Chromium). Looks good to me!

**Comment by mariusnita** [comment] 2024-03-02 05:35
Sweet, thanks!

**Closed** 2024-03-02 05:36 UTC
